language: node_js
node_js:
  - "18"

services:
  - docker
  - mongodb

before_install:
  - docker build --target production -t task-management-system .

script:
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "main" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag task-management-system $DOCKER_USERNAME/task-management-system;
      docker push $DOCKER_USERNAME/task-management-system;
    fi
